language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls